# Generated by Django 4.2.11 on 2024-04-26 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='periodicity',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='периодичность'),
        ),
    ]
