# Generated by Django 4.2.11 on 2024-04-26 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_alter_habit_periodicity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='execute_time',
            field=models.PositiveSmallIntegerField(blank=True, default=120, null=True, verbose_name='время на выполнение'),
        ),
    ]
