# Generated by Django 4.2.11 on 2024-04-30 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0004_alter_habit_execute_time_alter_habit_periodicity'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='last_notification',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время последнего оповещения'),
        ),
    ]
